-- supabase/baseline/v1_baseline.sql
-- AUTO-GENERATED by scripts/build-v1-baseline.py from supabase/remote-v1-backup.sql
-- (the v1 pre-v2 database snapshot). Contains ONLY the v1 objects that NO migration
-- creates, so a from-scratch rebuild can apply the v2 migration chain.
--
-- This is NOT a committed migration. CI (.github/workflows/ci.yml) and the local
-- `npm run db:rebuild` script stage it as
--   supabase/migrations/20260519230001_v1_baseline.sql
-- (immediately after the v1->v2 bridge, before the first migration that references a
-- v1 object), then run `supabase start` / `supabase db reset`. It runs on a FRESH
-- database only, so it intentionally uses plain DDL with no idempotency guards.
--
-- Do NOT edit by hand and do NOT commit the staged migrations/ copy (it is gitignored).
-- Regenerate with: python3 scripts/build-v1-baseline.py

-- ===== functions =====
CREATE OR REPLACE FUNCTION "public"."advisory_lock_fixture"("lock_key" bigint) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
begin
  perform pg_advisory_xact_lock(lock_key);
end;
$$;

CREATE OR REPLACE FUNCTION "public"."inspect_worker_db_context"() RETURNS TABLE("is_replica" boolean, "isolation" "text", "txn" bigint, "ts" timestamp with time zone)
    LANGUAGE "sql" SECURITY DEFINER
    AS $$
  select
    pg_is_in_recovery() as is_replica,
    current_setting('transaction_isolation') as isolation,
    txid_current() as txn,
    now() as ts;
$$;

CREATE OR REPLACE FUNCTION "public"."purge_user_auth_snapshot"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public', 'pg_temp'
    AS $$
begin
  delete from public.user_auth_snapshot where user_id = old.id;
  return old;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."sync_user_auth_snapshot"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public', 'pg_temp'
    AS $$
begin
  insert into public.user_auth_snapshot (user_id, email, status, created_at, last_sign_in_at, updated_at)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'status', 'active'),
    new.created_at,
    new.last_sign_in_at,
    now()
  )
  on conflict (user_id) do update
  set email = excluded.email,
      status = excluded.status,
      created_at = excluded.created_at,
      last_sign_in_at = excluded.last_sign_in_at,
      updated_at = now();
  return new;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."touch_link_in_bio_updated_at"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ===== tables =====
CREATE TABLE IF NOT EXISTS "public"."ad_sets" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "campaign_id" "uuid" NOT NULL,
    "meta_adset_id" "text",
    "name" "text" NOT NULL,
    "targeting" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "placements" "jsonb" DEFAULT '"AUTO"'::"jsonb" NOT NULL,
    "budget_amount" numeric,
    "optimisation_goal" "text" NOT NULL,
    "bid_strategy" "text" DEFAULT 'LOWEST_COST_WITHOUT_CAP'::"text" NOT NULL,
    "status" "text" DEFAULT 'DRAFT'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "phase_start" "date",
    "phase_end" "date",
    "adset_media_asset_id" "uuid",
    "adset_image_url" "text",
    "ads_stop_time" time without time zone,
    "meta_status" "text",
    "metrics_spend" numeric DEFAULT 0 NOT NULL,
    "metrics_impressions" integer DEFAULT 0 NOT NULL,
    "metrics_reach" integer DEFAULT 0 NOT NULL,
    "metrics_clicks" integer DEFAULT 0 NOT NULL,
    "metrics_ctr" numeric DEFAULT 0 NOT NULL,
    "metrics_cpc" numeric DEFAULT 0 NOT NULL,
    "last_synced_at" timestamp with time zone,
    "metrics_conversions" numeric DEFAULT 0 NOT NULL,
    "metrics_cost_per_conversion" numeric DEFAULT 0 NOT NULL,
    "metrics_conversion_rate" numeric DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."ads" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "adset_id" "uuid" NOT NULL,
    "meta_ad_id" "text",
    "meta_creative_id" "text",
    "name" "text" NOT NULL,
    "headline" "text" NOT NULL,
    "primary_text" "text" NOT NULL,
    "description" "text" NOT NULL,
    "cta" "text" DEFAULT 'LEARN_MORE'::"text" NOT NULL,
    "media_asset_id" "uuid",
    "creative_brief" "text",
    "preview_url" "text",
    "status" "text" DEFAULT 'DRAFT'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "angle" "text",
    "meta_status" "text",
    "metrics_spend" numeric DEFAULT 0 NOT NULL,
    "metrics_impressions" integer DEFAULT 0 NOT NULL,
    "metrics_reach" integer DEFAULT 0 NOT NULL,
    "metrics_clicks" integer DEFAULT 0 NOT NULL,
    "metrics_ctr" numeric DEFAULT 0 NOT NULL,
    "metrics_cpc" numeric DEFAULT 0 NOT NULL,
    "last_synced_at" timestamp with time zone,
    "metrics_conversions" numeric DEFAULT 0 NOT NULL,
    "metrics_cost_per_conversion" numeric DEFAULT 0 NOT NULL,
    "metrics_conversion_rate" numeric DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."auth_rate_limits" (
    "key" "text" NOT NULL,
    "count" integer DEFAULT 0 NOT NULL,
    "reset_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."booking_conversion_events" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "account_id" "uuid" NOT NULL,
    "source_site" "text" DEFAULT 'the-anchor.pub'::"text" NOT NULL,
    "booking_id" "text" NOT NULL,
    "meta_event_id" "text",
    "booking_type" "text" DEFAULT 'event'::"text" NOT NULL,
    "event_id" "text",
    "event_slug" "text",
    "event_name" "text",
    "event_category_name" "text",
    "event_category_slug" "text",
    "event_date" "date",
    "tickets" integer,
    "value" numeric,
    "currency" "text" DEFAULT 'GBP'::"text" NOT NULL,
    "food_intent" "text",
    "source_url" "text",
    "landing_path" "text",
    "utm_source" "text",
    "utm_medium" "text",
    "utm_campaign" "text",
    "utm_content" "text",
    "utm_term" "text",
    "fbclid" "text",
    "occurred_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "booking_conversion_events_booking_type_check" CHECK (("booking_type" = ANY (ARRAY['event'::"text", 'table'::"text"]))),
    CONSTRAINT "booking_conversion_events_tickets_check" CHECK ((("tickets" IS NULL) OR ("tickets" > 0)))
);

CREATE TABLE IF NOT EXISTS "public"."brand_profile" (
    "account_id" "uuid" NOT NULL,
    "tone_formal" numeric(3,2) DEFAULT 0.50 NOT NULL,
    "tone_playful" numeric(3,2) DEFAULT 0.50 NOT NULL,
    "key_phrases" "text"[] DEFAULT ARRAY[]::"text"[],
    "banned_topics" "text"[] DEFAULT ARRAY[]::"text"[],
    "default_hashtags" "text"[] DEFAULT ARRAY[]::"text"[],
    "default_emojis" "text"[] DEFAULT ARRAY[]::"text"[],
    "instagram_signature" "text",
    "facebook_signature" "text",
    "gbp_cta" "text",
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "banned_phrases" "text"[] DEFAULT '{}'::"text"[] NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."campaigns" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "account_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "campaign_type" "text" NOT NULL,
    "start_at" timestamp with time zone,
    "end_at" timestamp with time zone,
    "hero_media_id" "uuid",
    "auto_confirm" boolean DEFAULT false NOT NULL,
    "status" "text" DEFAULT 'draft'::"text" NOT NULL,
    "metadata" "jsonb",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "link_in_bio_url" "text",
    CONSTRAINT "campaigns_campaign_type_check" CHECK (("campaign_type" = ANY (ARRAY['event'::"text", 'promotion'::"text", 'weekly'::"text", 'instant'::"text"]))),
    CONSTRAINT "campaigns_status_check" CHECK (("status" = ANY (ARRAY['draft'::"text", 'scheduled'::"text", 'completed'::"text", 'cancelled'::"text"])))
);

CREATE TABLE IF NOT EXISTS "public"."content_templates" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "account_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "prompt" "text" NOT NULL,
    "platforms" "text"[] DEFAULT '{}'::"text"[] NOT NULL,
    "tone_adjust" "text" DEFAULT 'default'::"text" NOT NULL,
    "cta_url" "text",
    "notes" "text",
    "use_count" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."content_variants" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "content_item_id" "uuid" NOT NULL,
    "body" "text",
    "media_ids" "uuid"[] DEFAULT ARRAY[]::"uuid"[],
    "preview_data" "jsonb",
    "validation" "jsonb",
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "banner_enabled" boolean,
    "banner_text_override" "text",
    "banner_position" "text",
    "banner_bg" "text",
    "banner_text_colour" "text",
    CONSTRAINT "content_variants_banner_bg_check" CHECK ((("banner_bg" IS NULL) OR ("banner_bg" ~ '^#[0-9A-Fa-f]{6}$'::"text"))),
    CONSTRAINT "content_variants_banner_position_check" CHECK ((("banner_position" IS NULL) OR ("banner_position" = ANY (ARRAY['top'::"text", 'bottom'::"text", 'left'::"text", 'right'::"text"])))),
    CONSTRAINT "content_variants_banner_text_colour_check" CHECK ((("banner_text_colour" IS NULL) OR ("banner_text_colour" ~ '^#[0-9A-Fa-f]{6}$'::"text"))),
    CONSTRAINT "content_variants_banner_text_override_check" CHECK ((("banner_text_override" IS NULL) OR ("char_length"("banner_text_override") <= 20)))
);

CREATE TABLE IF NOT EXISTS "public"."gbp_reviews" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "business_profile_id" "uuid" NOT NULL,
    "google_review_id" "text" NOT NULL,
    "reviewer_name" "text" DEFAULT ''::"text" NOT NULL,
    "star_rating" integer NOT NULL,
    "comment" "text",
    "create_time" timestamp with time zone NOT NULL,
    "update_time" timestamp with time zone NOT NULL,
    "reply_comment" "text",
    "reply_update_time" timestamp with time zone,
    "ai_draft" "text",
    "status" "text" DEFAULT 'pending'::"text" NOT NULL,
    "synced_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "gbp_reviews_star_rating_check" CHECK ((("star_rating" >= 1) AND ("star_rating" <= 5))),
    CONSTRAINT "gbp_reviews_status_check" CHECK (("status" = ANY (ARRAY['pending'::"text", 'draft_ready'::"text", 'replied'::"text"])))
);

CREATE TABLE IF NOT EXISTS "public"."management_app_connections" (
    "account_id" "uuid" NOT NULL,
    "base_url" "text" NOT NULL,
    "api_key" "text" NOT NULL,
    "enabled" boolean DEFAULT true NOT NULL,
    "last_tested_at" timestamp with time zone,
    "last_test_status" "text",
    "last_test_message" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "management_app_connections_last_test_status_check" CHECK ((("last_test_status" = ANY (ARRAY['ok'::"text", 'error'::"text"])) OR ("last_test_status" IS NULL)))
);

CREATE TABLE IF NOT EXISTS "public"."media_assets" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "account_id" "uuid" NOT NULL,
    "storage_path" "text" NOT NULL,
    "file_name" "text" NOT NULL,
    "media_type" "text" NOT NULL,
    "mime_type" "text",
    "size_bytes" bigint,
    "tags" "text"[] DEFAULT ARRAY[]::"text"[],
    "uploaded_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "processed_status" "text" DEFAULT 'pending'::"text" NOT NULL,
    "processed_at" timestamp with time zone,
    "derived_variants" "jsonb" DEFAULT '{}'::"jsonb",
    "hidden_at" timestamp with time zone,
    "aspect_class" "text" DEFAULT 'square'::"text" NOT NULL,
    CONSTRAINT "media_assets_aspect_class_check" CHECK (("aspect_class" = ANY (ARRAY['square'::"text", 'story'::"text", 'landscape'::"text"]))),
    CONSTRAINT "media_assets_media_type_check" CHECK (("media_type" = ANY (ARRAY['image'::"text", 'video'::"text"]))),
    CONSTRAINT "media_assets_processed_status_check" CHECK (("processed_status" = ANY (ARRAY['pending'::"text", 'processing'::"text", 'ready'::"text", 'failed'::"text", 'skipped'::"text"])))
);

CREATE TABLE IF NOT EXISTS "public"."meta_ad_accounts" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "account_id" "uuid" NOT NULL,
    "meta_account_id" "text" DEFAULT ''::"text" NOT NULL,
    "currency" "text" DEFAULT 'GBP'::"text" NOT NULL,
    "timezone" "text" DEFAULT 'Europe/London'::"text" NOT NULL,
    "access_token" "text" DEFAULT ''::"text" NOT NULL,
    "token_expires_at" timestamp with time zone,
    "setup_complete" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "meta_pixel_id" "text" DEFAULT '757659911002159'::"text" NOT NULL,
    "conversion_event_name" "text" DEFAULT 'Purchase'::"text" NOT NULL,
    "conversion_optimisation_enabled" boolean DEFAULT true NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."meta_campaigns" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "account_id" "uuid" NOT NULL,
    "meta_campaign_id" "text",
    "name" "text" NOT NULL,
    "objective" "text" NOT NULL,
    "problem_brief" "text" NOT NULL,
    "ai_rationale" "text",
    "budget_type" "text" DEFAULT 'DAILY'::"text" NOT NULL,
    "budget_amount" numeric NOT NULL,
    "start_date" "date" NOT NULL,
    "end_date" "date",
    "status" "text" DEFAULT 'DRAFT'::"text" NOT NULL,
    "meta_status" "text",
    "special_ad_category" "text" DEFAULT 'NONE'::"text" NOT NULL,
    "last_synced_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "publish_error" "text",
    "campaign_kind" "text" DEFAULT 'event'::"text" NOT NULL,
    "source_type" "text",
    "source_id" "text",
    "destination_url" "text",
    "source_snapshot" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "metrics_spend" numeric DEFAULT 0 NOT NULL,
    "metrics_impressions" integer DEFAULT 0 NOT NULL,
    "metrics_reach" integer DEFAULT 0 NOT NULL,
    "metrics_clicks" integer DEFAULT 0 NOT NULL,
    "metrics_ctr" numeric DEFAULT 0 NOT NULL,
    "metrics_cpc" numeric DEFAULT 0 NOT NULL,
    "geo_radius_miles" integer DEFAULT 3 NOT NULL,
    "audience_mode" "text" DEFAULT 'local_only'::"text" NOT NULL,
    "audience_interest_keywords" "text"[] DEFAULT '{}'::"text"[] NOT NULL,
    "resolved_interests" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "metrics_conversions" numeric DEFAULT 0 NOT NULL,
    "metrics_cost_per_conversion" numeric DEFAULT 0 NOT NULL,
    "metrics_conversion_rate" numeric DEFAULT 0 NOT NULL,
    CONSTRAINT "meta_campaigns_audience_mode_check" CHECK (("audience_mode" = ANY (ARRAY['local_only'::"text", 'local_interests'::"text"]))),
    CONSTRAINT "meta_campaigns_campaign_kind_check" CHECK (("campaign_kind" = ANY (ARRAY['event'::"text", 'evergreen'::"text"]))),
    CONSTRAINT "meta_campaigns_geo_radius_miles_check" CHECK (("geo_radius_miles" = ANY (ARRAY[1, 3, 5, 10])))
);

CREATE TABLE IF NOT EXISTS "public"."meta_optimisation_actions" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "run_id" "uuid" NOT NULL,
    "account_id" "uuid" NOT NULL,
    "campaign_id" "uuid" NOT NULL,
    "adset_id" "uuid",
    "ad_id" "uuid",
    "meta_object_id" "text",
    "action_type" "text" NOT NULL,
    "reason" "text" NOT NULL,
    "metrics_snapshot" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "status" "text" DEFAULT 'planned'::"text" NOT NULL,
    "error" "text",
    "applied_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "recommendation_payload" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "replacement_ad_id" "uuid",
    "severity" "text" DEFAULT 'info'::"text" NOT NULL,
    CONSTRAINT "meta_optimisation_actions_action_type_check" CHECK (("action_type" = ANY (ARRAY['pause_ad'::"text", 'tracking_issue'::"text", 'copy_rewrite'::"text"]))),
    CONSTRAINT "meta_optimisation_actions_severity_check" CHECK (("severity" = ANY (ARRAY['info'::"text", 'warning'::"text", 'critical'::"text"]))),
    CONSTRAINT "meta_optimisation_actions_status_check" CHECK (("status" = ANY (ARRAY['planned'::"text", 'applied'::"text", 'skipped'::"text", 'failed'::"text"])))
);

CREATE TABLE IF NOT EXISTS "public"."meta_optimisation_runs" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "account_id" "uuid" NOT NULL,
    "mode" "text" DEFAULT 'apply'::"text" NOT NULL,
    "status" "text" DEFAULT 'running'::"text" NOT NULL,
    "summary" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "error" "text",
    "started_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "finished_at" timestamp with time zone,
    CONSTRAINT "meta_optimisation_runs_mode_check" CHECK (("mode" = ANY (ARRAY['apply'::"text", 'dry_run'::"text", 'recommend'::"text"]))),
    CONSTRAINT "meta_optimisation_runs_status_check" CHECK (("status" = ANY (ARRAY['running'::"text", 'completed'::"text", 'failed'::"text"])))
);

CREATE TABLE IF NOT EXISTS "public"."posting_defaults" (
    "account_id" "uuid" NOT NULL,
    "facebook_location_id" "text",
    "instagram_location_id" "text",
    "gbp_location_id" "text",
    "notifications" "jsonb" DEFAULT "jsonb_build_object"('emailFailures', true, 'emailTokenExpiring', true) NOT NULL,
    "gbp_cta_standard" "text" DEFAULT 'LEARN_MORE'::"text" NOT NULL,
    "gbp_cta_event" "text" DEFAULT 'LEARN_MORE'::"text" NOT NULL,
    "gbp_cta_offer" "text" DEFAULT 'REDEEM'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "default_posting_time" "text",
    "venue_location" "text",
    "venue_latitude" numeric(9,6),
    "venue_longitude" numeric(9,6),
    "banners_enabled" boolean DEFAULT true NOT NULL,
    "banner_position" "text" DEFAULT 'right'::"text" NOT NULL,
    "banner_bg" "text" DEFAULT '#a57626'::"text" NOT NULL,
    "banner_text_colour" "text" DEFAULT '#FFFFFF'::"text" NOT NULL,
    CONSTRAINT "posting_defaults_banner_bg_check" CHECK (("banner_bg" ~ '^#[0-9A-Fa-f]{6}$'::"text")),
    CONSTRAINT "posting_defaults_banner_position_check" CHECK (("banner_position" = ANY (ARRAY['top'::"text", 'bottom'::"text", 'left'::"text", 'right'::"text"]))),
    CONSTRAINT "posting_defaults_banner_text_colour_check" CHECK (("banner_text_colour" ~ '^#[0-9A-Fa-f]{6}$'::"text")),
    CONSTRAINT "posting_defaults_default_posting_time_check" CHECK ((("default_posting_time" IS NULL) OR ("default_posting_time" ~ '^([01]\d|2[0-3]):[0-5]\d$'::"text"))),
    CONSTRAINT "posting_defaults_venue_latitude_check" CHECK ((("venue_latitude" IS NULL) OR (("venue_latitude" >= ('-90'::integer)::numeric) AND ("venue_latitude" <= (90)::numeric)))),
    CONSTRAINT "posting_defaults_venue_location_check" CHECK ((("venue_location" IS NULL) OR ("length"("venue_location") <= 100))),
    CONSTRAINT "posting_defaults_venue_longitude_check" CHECK ((("venue_longitude" IS NULL) OR (("venue_longitude" >= ('-180'::integer)::numeric) AND ("venue_longitude" <= (180)::numeric))))
);

CREATE TABLE IF NOT EXISTS "public"."tournament_fixtures" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "tournament_id" "uuid" NOT NULL,
    "match_number" integer NOT NULL,
    "round" "text" NOT NULL,
    "group_name" "text",
    "team_a" "text" NOT NULL,
    "team_b" "text" NOT NULL,
    "teams_confirmed" boolean DEFAULT false NOT NULL,
    "kick_off_at" timestamp with time zone NOT NULL,
    "venue_city" "text",
    "showing" boolean DEFAULT false NOT NULL,
    "showing_note" "text",
    "booking_url" "text",
    "content_generated" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "tournament_fixtures_booking_url_check" CHECK ((("booking_url" IS NULL) OR ("booking_url" ~~ 'https://%'::"text"))),
    CONSTRAINT "tournament_fixtures_round_check" CHECK (("round" = ANY (ARRAY['group_stage'::"text", 'round_of_32'::"text", 'round_of_16'::"text", 'quarter_final'::"text", 'semi_final'::"text", 'third_place'::"text", 'final'::"text"]))),
    CONSTRAINT "tournament_fixtures_team_a_check" CHECK (("char_length"("team_a") <= 50)),
    CONSTRAINT "tournament_fixtures_team_b_check" CHECK (("char_length"("team_b") <= 50))
);

CREATE TABLE IF NOT EXISTS "public"."tournaments" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "account_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "slug" "text" NOT NULL,
    "status" "text" DEFAULT 'draft'::"text" NOT NULL,
    "base_image_square_id" "uuid",
    "base_image_story_id" "uuid",
    "house_rules_text" "text",
    "post_template" "text" NOT NULL,
    "platforms" "text"[] DEFAULT '{instagram,facebook}'::"text"[] NOT NULL,
    "post_lead_hours" integer DEFAULT 24 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "feed_api_key" "text",
    CONSTRAINT "tournaments_house_rules_text_check" CHECK (("char_length"("house_rules_text") <= 200)),
    CONSTRAINT "tournaments_post_template_check" CHECK (("char_length"("post_template") <= 500)),
    CONSTRAINT "tournaments_status_check" CHECK (("status" = ANY (ARRAY['draft'::"text", 'active'::"text", 'archived'::"text"])))
);

CREATE TABLE IF NOT EXISTS "public"."user_auth_snapshot" (
    "user_id" "uuid" NOT NULL,
    "email" "text" NOT NULL,
    "status" "text" DEFAULT 'active'::"text" NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "last_sign_in_at" timestamp with time zone,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."worker_heartbeats" (
    "name" "text" NOT NULL,
    "last_run_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "last_run_source" "text",
    "metadata" "jsonb",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

-- ===== constraints =====
ALTER TABLE ONLY "public"."ad_sets"
    ADD CONSTRAINT "ad_sets_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."ads"
    ADD CONSTRAINT "ads_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."auth_rate_limits"
    ADD CONSTRAINT "auth_rate_limits_pkey" PRIMARY KEY ("key");

ALTER TABLE ONLY "public"."booking_conversion_events"
    ADD CONSTRAINT "booking_conversion_events_account_booking_key" UNIQUE ("account_id", "booking_id");

ALTER TABLE ONLY "public"."booking_conversion_events"
    ADD CONSTRAINT "booking_conversion_events_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."brand_profile"
    ADD CONSTRAINT "brand_profile_pkey" PRIMARY KEY ("account_id");

ALTER TABLE ONLY "public"."campaigns"
    ADD CONSTRAINT "campaigns_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."content_templates"
    ADD CONSTRAINT "content_templates_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."content_variants"
    ADD CONSTRAINT "content_variants_content_item_id_key" UNIQUE ("content_item_id");

ALTER TABLE ONLY "public"."content_variants"
    ADD CONSTRAINT "content_variants_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tournament_fixtures"
    ADD CONSTRAINT "fixtures_tournament_match_unique" UNIQUE ("tournament_id", "match_number");

ALTER TABLE ONLY "public"."gbp_reviews"
    ADD CONSTRAINT "gbp_reviews_business_review_unique" UNIQUE ("business_profile_id", "google_review_id");

ALTER TABLE ONLY "public"."gbp_reviews"
    ADD CONSTRAINT "gbp_reviews_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."management_app_connections"
    ADD CONSTRAINT "management_app_connections_pkey" PRIMARY KEY ("account_id");

ALTER TABLE ONLY "public"."media_assets"
    ADD CONSTRAINT "media_assets_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."meta_ad_accounts"
    ADD CONSTRAINT "meta_ad_accounts_account_id_key" UNIQUE ("account_id");

ALTER TABLE ONLY "public"."meta_ad_accounts"
    ADD CONSTRAINT "meta_ad_accounts_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."meta_campaigns"
    ADD CONSTRAINT "meta_campaigns_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."meta_optimisation_actions"
    ADD CONSTRAINT "meta_optimisation_actions_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."meta_optimisation_runs"
    ADD CONSTRAINT "meta_optimisation_runs_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."posting_defaults"
    ADD CONSTRAINT "posting_defaults_pkey" PRIMARY KEY ("account_id");

ALTER TABLE ONLY "public"."tournament_fixtures"
    ADD CONSTRAINT "tournament_fixtures_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tournaments"
    ADD CONSTRAINT "tournaments_account_slug_unique" UNIQUE ("account_id", "slug");

ALTER TABLE ONLY "public"."tournaments"
    ADD CONSTRAINT "tournaments_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."user_auth_snapshot"
    ADD CONSTRAINT "user_auth_snapshot_pkey" PRIMARY KEY ("user_id");

ALTER TABLE ONLY "public"."worker_heartbeats"
    ADD CONSTRAINT "worker_heartbeats_pkey" PRIMARY KEY ("name");

ALTER TABLE ONLY "public"."ad_sets"
    ADD CONSTRAINT "ad_sets_adset_media_asset_id_fkey" FOREIGN KEY ("adset_media_asset_id") REFERENCES "public"."media_assets"("id");

ALTER TABLE ONLY "public"."ad_sets"
    ADD CONSTRAINT "ad_sets_campaign_id_fkey" FOREIGN KEY ("campaign_id") REFERENCES "public"."meta_campaigns"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."ads"
    ADD CONSTRAINT "ads_adset_id_fkey" FOREIGN KEY ("adset_id") REFERENCES "public"."ad_sets"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."booking_conversion_events"
    ADD CONSTRAINT "booking_conversion_events_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."brand_profile"
    ADD CONSTRAINT "brand_profile_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."campaigns"
    ADD CONSTRAINT "campaigns_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."campaigns"
    ADD CONSTRAINT "campaigns_hero_media_id_fkey" FOREIGN KEY ("hero_media_id") REFERENCES "public"."media_assets"("id");

ALTER TABLE ONLY "public"."content_templates"
    ADD CONSTRAINT "content_templates_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."content_variants"
    ADD CONSTRAINT "content_variants_content_item_id_fkey" FOREIGN KEY ("content_item_id") REFERENCES "public"."content_items"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."gbp_reviews"
    ADD CONSTRAINT "gbp_reviews_business_profile_id_fkey" FOREIGN KEY ("business_profile_id") REFERENCES "public"."accounts"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."management_app_connections"
    ADD CONSTRAINT "management_app_connections_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."media_assets"
    ADD CONSTRAINT "media_assets_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."meta_ad_accounts"
    ADD CONSTRAINT "meta_ad_accounts_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."meta_campaigns"
    ADD CONSTRAINT "meta_campaigns_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."meta_optimisation_actions"
    ADD CONSTRAINT "meta_optimisation_actions_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."meta_optimisation_actions"
    ADD CONSTRAINT "meta_optimisation_actions_ad_id_fkey" FOREIGN KEY ("ad_id") REFERENCES "public"."ads"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."meta_optimisation_actions"
    ADD CONSTRAINT "meta_optimisation_actions_adset_id_fkey" FOREIGN KEY ("adset_id") REFERENCES "public"."ad_sets"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."meta_optimisation_actions"
    ADD CONSTRAINT "meta_optimisation_actions_campaign_id_fkey" FOREIGN KEY ("campaign_id") REFERENCES "public"."meta_campaigns"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."meta_optimisation_actions"
    ADD CONSTRAINT "meta_optimisation_actions_replacement_ad_id_fkey" FOREIGN KEY ("replacement_ad_id") REFERENCES "public"."ads"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."meta_optimisation_actions"
    ADD CONSTRAINT "meta_optimisation_actions_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES "public"."meta_optimisation_runs"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."meta_optimisation_runs"
    ADD CONSTRAINT "meta_optimisation_runs_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."posting_defaults"
    ADD CONSTRAINT "posting_defaults_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."tournament_fixtures"
    ADD CONSTRAINT "tournament_fixtures_tournament_id_fkey" FOREIGN KEY ("tournament_id") REFERENCES "public"."tournaments"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."tournaments"
    ADD CONSTRAINT "tournaments_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."tournaments"
    ADD CONSTRAINT "tournaments_base_image_square_id_fkey" FOREIGN KEY ("base_image_square_id") REFERENCES "public"."media_assets"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."tournaments"
    ADD CONSTRAINT "tournaments_base_image_story_id_fkey" FOREIGN KEY ("base_image_story_id") REFERENCES "public"."media_assets"("id") ON DELETE SET NULL;

-- ===== indexes =====
CREATE INDEX "auth_rate_limits_reset_at_idx" ON "public"."auth_rate_limits" USING "btree" ("reset_at");

CREATE INDEX "booking_conversion_events_account_category_idx" ON "public"."booking_conversion_events" USING "btree" ("account_id", "event_category_slug", "occurred_at" DESC);

CREATE INDEX "booking_conversion_events_account_event_idx" ON "public"."booking_conversion_events" USING "btree" ("account_id", "event_id", "occurred_at" DESC);

CREATE INDEX "booking_conversion_events_account_occurred_idx" ON "public"."booking_conversion_events" USING "btree" ("account_id", "occurred_at" DESC);

CREATE INDEX "booking_conversion_events_utm_campaign_idx" ON "public"."booking_conversion_events" USING "btree" ("account_id", "utm_campaign", "occurred_at" DESC);

CREATE INDEX "campaigns_account_idx" ON "public"."campaigns" USING "btree" ("account_id");

CREATE INDEX "campaigns_link_in_bio_url_idx" ON "public"."campaigns" USING "btree" ("account_id", "link_in_bio_url");

CREATE INDEX "campaigns_status_idx" ON "public"."campaigns" USING "btree" ("status");

CREATE INDEX "content_templates_account_idx" ON "public"."content_templates" USING "btree" ("account_id", "updated_at" DESC);

CREATE INDEX "content_variants_content_idx" ON "public"."content_variants" USING "btree" ("content_item_id");

CREATE INDEX "gbp_reviews_account_create_time_idx" ON "public"."gbp_reviews" USING "btree" ("business_profile_id", "create_time" DESC);

CREATE INDEX "idx_fixtures_tournament_filter" ON "public"."tournament_fixtures" USING "btree" ("tournament_id", "showing", "teams_confirmed");

CREATE INDEX "idx_fixtures_tournament_kickoff" ON "public"."tournament_fixtures" USING "btree" ("tournament_id", "kick_off_at");

CREATE INDEX "idx_tournaments_account" ON "public"."tournaments" USING "btree" ("account_id");

CREATE UNIQUE INDEX "idx_tournaments_feed_api_key" ON "public"."tournaments" USING "btree" ("feed_api_key") WHERE ("feed_api_key" IS NOT NULL);

CREATE INDEX "media_assets_account_idx" ON "public"."media_assets" USING "btree" ("account_id");

CREATE INDEX "media_assets_hidden_idx" ON "public"."media_assets" USING "btree" ("account_id", "hidden_at");

CREATE INDEX "media_assets_processed_status_idx" ON "public"."media_assets" USING "btree" ("processed_status");

CREATE INDEX "media_assets_uploaded_idx" ON "public"."media_assets" USING "btree" ("uploaded_at" DESC);

CREATE INDEX "meta_campaigns_campaign_kind_idx" ON "public"."meta_campaigns" USING "btree" ("campaign_kind");

CREATE INDEX "meta_campaigns_source_lookup_idx" ON "public"."meta_campaigns" USING "btree" ("source_type", "source_id");

CREATE INDEX "meta_optimisation_actions_account_created_idx" ON "public"."meta_optimisation_actions" USING "btree" ("account_id", "created_at" DESC);

CREATE INDEX "meta_optimisation_actions_campaign_idx" ON "public"."meta_optimisation_actions" USING "btree" ("campaign_id", "created_at" DESC);

CREATE INDEX "meta_optimisation_actions_replacement_ad_idx" ON "public"."meta_optimisation_actions" USING "btree" ("replacement_ad_id");

CREATE INDEX "meta_optimisation_runs_account_started_idx" ON "public"."meta_optimisation_runs" USING "btree" ("account_id", "started_at" DESC);

-- ===== row level security =====
ALTER TABLE ONLY "public"."user_auth_snapshot" FORCE ROW LEVEL SECURITY;

ALTER TABLE "public"."ad_sets" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."ads" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."auth_rate_limits" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."booking_conversion_events" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."brand_profile" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."campaigns" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."content_templates" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."content_variants" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."gbp_reviews" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."management_app_connections" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."media_assets" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."meta_ad_accounts" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."meta_campaigns" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."meta_optimisation_actions" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."meta_optimisation_runs" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."posting_defaults" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tournament_fixtures" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tournaments" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."user_auth_snapshot" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."worker_heartbeats" ENABLE ROW LEVEL SECURITY;

-- ===== policies =====
CREATE POLICY "Auth rate limits service only" ON "public"."auth_rate_limits" USING (("auth"."role"() = 'service_role'::"text")) WITH CHECK (("auth"."role"() = 'service_role'::"text"));

CREATE POLICY "Brand profile accessible by account" ON "public"."brand_profile" USING ((("auth"."role"() = 'service_role'::"text") OR ("account_id" = "public"."current_account_id"()))) WITH CHECK ((("auth"."role"() = 'service_role'::"text") OR ("account_id" = "public"."current_account_id"())));

CREATE POLICY "Campaigns accessible by account" ON "public"."campaigns" USING ((("auth"."role"() = 'service_role'::"text") OR ("account_id" = "public"."current_account_id"()))) WITH CHECK ((("auth"."role"() = 'service_role'::"text") OR ("account_id" = "public"."current_account_id"())));

CREATE POLICY "Content templates accessible by account" ON "public"."content_templates" USING ((("auth"."role"() = 'service_role'::"text") OR ("account_id" = "public"."current_account_id"()))) WITH CHECK ((("auth"."role"() = 'service_role'::"text") OR ("account_id" = "public"."current_account_id"())));

CREATE POLICY "Content variants accessible via parent" ON "public"."content_variants" USING ((("auth"."role"() = 'service_role'::"text") OR (EXISTS ( SELECT 1
   FROM "public"."content_items" "ci"
  WHERE (("ci"."id" = "content_variants"."content_item_id") AND ("ci"."account_id" = "public"."current_account_id"())))))) WITH CHECK ((("auth"."role"() = 'service_role'::"text") OR (EXISTS ( SELECT 1
   FROM "public"."content_items" "ci"
  WHERE (("ci"."id" = "content_variants"."content_item_id") AND ("ci"."account_id" = "public"."current_account_id"()))))));

CREATE POLICY "Fixtures accessible via tournament account" ON "public"."tournament_fixtures" USING ((("auth"."role"() = 'service_role'::"text") OR (EXISTS ( SELECT 1
   FROM "public"."tournaments" "t"
  WHERE (("t"."id" = "tournament_fixtures"."tournament_id") AND ("t"."account_id" = "public"."current_account_id"())))))) WITH CHECK ((("auth"."role"() = 'service_role'::"text") OR (EXISTS ( SELECT 1
   FROM "public"."tournaments" "t"
  WHERE (("t"."id" = "tournament_fixtures"."tournament_id") AND ("t"."account_id" = "public"."current_account_id"()))))));

CREATE POLICY "Management app connections service only" ON "public"."management_app_connections" USING (("auth"."role"() = 'service_role'::"text")) WITH CHECK (("auth"."role"() = 'service_role'::"text"));

CREATE POLICY "Media assets accessible by account" ON "public"."media_assets" USING ((("auth"."role"() = 'service_role'::"text") OR ("account_id" = "public"."current_account_id"()))) WITH CHECK ((("auth"."role"() = 'service_role'::"text") OR ("account_id" = "public"."current_account_id"())));

CREATE POLICY "Posting defaults accessible by account" ON "public"."posting_defaults" USING ((("auth"."role"() = 'service_role'::"text") OR ("account_id" = "public"."current_account_id"()))) WITH CHECK ((("auth"."role"() = 'service_role'::"text") OR ("account_id" = "public"."current_account_id"())));

CREATE POLICY "Tournaments accessible by account owner" ON "public"."tournaments" USING ((("auth"."role"() = 'service_role'::"text") OR ("account_id" = "public"."current_account_id"()))) WITH CHECK ((("auth"."role"() = 'service_role'::"text") OR ("account_id" = "public"."current_account_id"())));

CREATE POLICY "User auth snapshot readable by authenticated" ON "public"."user_auth_snapshot" FOR SELECT TO "authenticated", "service_role" USING (true);

CREATE POLICY "Users can manage their own ad account" ON "public"."meta_ad_accounts" USING (("account_id" = "public"."current_account_id"()));

CREATE POLICY "Users can manage their own ad sets" ON "public"."ad_sets" USING ((EXISTS ( SELECT 1
   FROM "public"."campaigns" "c"
  WHERE (("c"."id" = "ad_sets"."campaign_id") AND ("c"."account_id" = "public"."current_account_id"())))));

CREATE POLICY "Users can manage their own ads" ON "public"."ads" USING ((EXISTS ( SELECT 1
   FROM ("public"."ad_sets" "ads2"
     JOIN "public"."campaigns" "c" ON (("c"."id" = "ads2"."campaign_id")))
  WHERE (("ads2"."id" = "ads"."adset_id") AND ("c"."account_id" = "public"."current_account_id"())))));

CREATE POLICY "Users can manage their own campaigns" ON "public"."campaigns" USING (("account_id" = "public"."current_account_id"()));

CREATE POLICY "Users can manage their own meta campaigns" ON "public"."meta_campaigns" USING (("account_id" = "public"."current_account_id"())) WITH CHECK (("account_id" = "public"."current_account_id"()));

CREATE POLICY "Users can read own reviews" ON "public"."gbp_reviews" FOR SELECT USING ((("auth"."role"() = 'service_role'::"text") OR ("business_profile_id" = "public"."current_account_id"())));

CREATE POLICY "Users can update own reviews" ON "public"."gbp_reviews" FOR UPDATE USING ((("auth"."role"() = 'service_role'::"text") OR ("business_profile_id" = "public"."current_account_id"()))) WITH CHECK ((("auth"."role"() = 'service_role'::"text") OR ("business_profile_id" = "public"."current_account_id"())));

CREATE POLICY "Users can view their own booking conversions" ON "public"."booking_conversion_events" FOR SELECT USING (("account_id" = "public"."current_account_id"()));

CREATE POLICY "Users can view their own optimisation actions" ON "public"."meta_optimisation_actions" USING (("account_id" = "public"."current_account_id"())) WITH CHECK (("account_id" = "public"."current_account_id"()));

CREATE POLICY "Users can view their own optimisation runs" ON "public"."meta_optimisation_runs" USING (("account_id" = "public"."current_account_id"())) WITH CHECK (("account_id" = "public"."current_account_id"()));

CREATE POLICY "Worker heartbeats managed by service role" ON "public"."worker_heartbeats" USING (("auth"."role"() = 'service_role'::"text")) WITH CHECK (("auth"."role"() = 'service_role'::"text"));

-- ===== triggers =====
CREATE OR REPLACE TRIGGER "tournament_fixtures_updated_at" BEFORE UPDATE ON "public"."tournament_fixtures" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();

CREATE OR REPLACE TRIGGER "tournaments_updated_at" BEFORE UPDATE ON "public"."tournaments" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();

-- ===== reconcile migration-owned columns the v1 view needs (IF NOT EXISTS; no-op on prod) =====
ALTER TABLE "public"."publish_jobs" ADD COLUMN IF NOT EXISTS "attempt" integer;

ALTER TABLE "public"."publish_jobs" ADD COLUMN IF NOT EXISTS "content_item_id" "uuid";

ALTER TABLE "public"."publish_jobs" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone;

ALTER TABLE "public"."publish_jobs" ADD COLUMN IF NOT EXISTS "id" "uuid";

ALTER TABLE "public"."publish_jobs" ADD COLUMN IF NOT EXISTS "last_error" "text";

ALTER TABLE "public"."publish_jobs" ADD COLUMN IF NOT EXISTS "next_attempt_at" timestamp with time zone;

ALTER TABLE "public"."publish_jobs" ADD COLUMN IF NOT EXISTS "placement" "text";

ALTER TABLE "public"."publish_jobs" ADD COLUMN IF NOT EXISTS "provider_response" "jsonb";

ALTER TABLE "public"."publish_jobs" ADD COLUMN IF NOT EXISTS "status" "text";

ALTER TABLE "public"."publish_jobs" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone;

ALTER TABLE "public"."publish_jobs" ADD COLUMN IF NOT EXISTS "variant_id" "uuid";

-- ===== views =====
CREATE OR REPLACE VIEW "public"."publish_jobs_with_variant" AS
 SELECT "pj"."id",
    "pj"."content_item_id",
    "pj"."attempt",
    "pj"."status",
    "pj"."last_error",
    "pj"."provider_response",
    "pj"."next_attempt_at",
    "pj"."created_at",
    "pj"."updated_at",
    "pj"."placement",
    "pj"."variant_id",
    "cv"."media_ids"
   FROM ("public"."publish_jobs" "pj"
     JOIN "public"."content_variants" "cv" ON (("cv"."id" = "pj"."variant_id")));

