/**
 * The reviewed allowlist of database objects the `anon` role can reach.
 *
 * WHAT THIS IS
 *   A committed record of exactly what the public anon key can touch in the
 *   `public` schema of the cheersai2.0 project, as reviewed by a human. Every
 *   entry below was read from the live catalogue and kept deliberately.
 *
 *   `tests/anon-access.test.ts` reads the live catalogue and fails when the
 *   database grants anon anything this file does not list, or grants more on a
 *   listed object than this file allows. The test skips with an explanation when
 *   no database connection is configured, so `npm test` stays runnable offline
 *   and the live check only speaks when it is pointed at a real project.
 *
 * WHY IT EXISTS
 *   The anon surface widens on its own. `pg_default_acl` on this project has
 *   `postgres` granting anon every table privilege on every NEW table in
 *   `public`, EXECUTE on every NEW function, and rwU on every NEW sequence.
 *   Nobody writes those grants. They arrive with the object. So a migration that
 *   adds a table or a function hands anon a key to it in the same breath, and no
 *   line of SQL in this repository records that it happened.
 *
 *   Two attempts to close specific holes are already in the migration history and
 *   BOTH failed, in mirror-image ways, because a Supabase function carries two
 *   separate grants:
 *
 *     20260527080658_lockdown_admin_functions_2026_05_27.sql revoked
 *     `increment_rate_limit` FROM anon but not FROM PUBLIC. `create function`
 *     grants PUBLIC its own EXECUTE and anon is a member of PUBLIC, so anon
 *     still executes it today.
 *
 *     20260714120000_multibrand_foundation.sql revoked `is_super_admin()` and
 *     `is_account_member(uuid)` FROM public but not FROM anon. The default ACL
 *     had already granted anon EXECUTE directly, so anon still executes them
 *     today too.
 *
 *   Both migrations read as though the hole was closed. Neither closed it. That
 *   is precisely the failure this file exists to make visible: the only way to
 *   know what anon can reach is to ask the live database, and the only way to
 *   notice a change is to compare that answer against a reviewed list.
 *
 * THIS APPLICATION IS MULTI-TENANT. THE TENANT BOUNDARY IS THE RULE.
 *   Every customer's brand voice, content, media, audit trail, encrypted social
 *   tokens and management-app API key live in the same tables, separated only by
 *   `account_id` and the RLS policies that check it. A grant that lets anon read
 *   or write across that boundary is not a configuration choice, it is a breach
 *   of one customer's data by another.
 *
 *   So: NOTHING THAT CROSSES A TENANT BOUNDARY MAY EVER BE ADDED TO
 *   `ANON_ALLOWLIST`. That means no SECURITY DEFINER function that accepts an
 *   account id and acts on it (those bypass RLS by design, so the account id is
 *   whatever the caller says it is), and none of the tables or functions that
 *   define the boundary itself. Those objects are named in `NEVER_ALLOWLIST`
 *   below and the test asserts the allowlist contains none of them, so a careless
 *   edit to this file fails rather than passing quietly. If one of them turns up
 *   in the live catalogue, the fix is a migration that revokes it, never an entry
 *   here.
 *
 * HOW TO UPDATE IT, DELIBERATELY
 *   1. Do not edit this file to make a failing test pass. A failure means the
 *      live database changed. Find out which migration changed it first.
 *   2. If the new reach is wanted, add the entry with a `why` that says which
 *      feature needs it and which migration granted it, in the same pull request
 *      as that migration.
 *   3. If the new reach is not wanted, write a migration that revokes it. For a
 *      function the shape that actually closes it is both revokes together,
 *      because of the two failures described above:
 *        revoke execute on function public.thing(args) from public, anon;
 *      For a table it is:
 *        revoke all on public.thing from anon;
 *      Adding the revoke to the SAME migration that creates the object is the
 *      only version that survives a rebuild, because the default ACL re-grants
 *      on every `create`.
 *   4. Re-run the check against the live project and paste the result into the
 *      pull request:
 *        SUPABASE_DB_URL='postgresql://...' npx vitest run tests/anon-access.test.ts
 *
 * A NOTE ON THE TABLE ENTRIES
 *   Anon holds all eight table privileges on all 39 listed tables. That is not a
 *   decision anyone here made: it is what the default ACL grants, and stripping
 *   it project-wide is a change with real blast radius. RLS is therefore the
 *   control, and every listed table has RLS enabled with policies. The `why` on
 *   each entry records what the table holds and what the RLS gate is, so a reader
 *   can see what would be exposed if that gate ever slipped. Every one of the 39
 *   was checked by running `set local role anon` and counting rows on 4 September
 *   2026: all 39 returned zero, including `content_items`, which holds 1212 rows
 *   to an owner. The check is self-validating, since a failed role switch would
 *   have returned the owner's counts.
 *
 *   The value of listing tables that anon cannot read is that a NEW table shows
 *   up here as a failure on the day it is created, while it is still empty and
 *   before anybody has written an RLS policy for it.
 *
 * A NOTE ON THE EXTENSION ENTRY
 *   `btree_gist` is installed into `public` and contributes 188 anon-executable
 *   functions. They are GiST index support routines: they take and return
 *   internal index types, touch no application data, and are granted to PUBLIC by
 *   the extension itself. Listing all 188 individually would bury the six
 *   application functions that actually matter, so the catalogue query rolls each
 *   extension up into a single entry and records how many functions it
 *   contributes. A version bump that adds functions changes that count and fails
 *   the check, and a NEW extension installed into `public` fails it as an
 *   unlisted object.
 *
 * EVIDENCE
 *   Read from project nbkjciurhvkfpcpatbnt (cheersai2.0, PostgreSQL 17.6) on
 *   4 September 2026, read-only. Nothing was granted, revoked or migrated to
 *   produce it.
 */

export type AnonObjectKind =
  | 'table'
  | 'view'
  | 'materialized view'
  | 'sequence'
  | 'function'
  | 'extension';

/** One object the live catalogue says anon can reach. */
export interface AnonCatalogueEntry {
  kind: AnonObjectKind;
  /**
   * Tables, views and sequences use the bare relation name. Functions use
   * `name(identity arguments)`, so an overload cannot hide behind its sibling.
   * Extensions use the extension name.
   */
  name: string;
  privileges: string[];
  /** Extensions only: how many anon-executable functions the extension owns. */
  objects?: number;
}

export interface AnonAllowlistEntry extends AnonCatalogueEntry {
  why: string;
}

/**
 * Every table privilege Postgres 17 can grant. MAINTAIN is 17 only, so the
 * catalogue query asks for it only when the server is new enough. The live
 * project is 17.6, so MAINTAIN is present in the readings below.
 */
export const TABLE_PRIVILEGES = [
  'SELECT',
  'INSERT',
  'UPDATE',
  'DELETE',
  'TRUNCATE',
  'REFERENCES',
  'TRIGGER',
] as const;

export const TABLE_PRIVILEGES_PG17 = [...TABLE_PRIVILEGES, 'MAINTAIN'] as const;

export const SEQUENCE_PRIVILEGES = ['SELECT', 'UPDATE', 'USAGE'] as const;

/**
 * What the default ACL hands anon on every table in `public`. All 39 listed
 * tables and the one listed view carry exactly this set and nothing else, which
 * is itself evidence that no table grant here was written deliberately.
 */
const SUPABASE_DEFAULT_TABLE_GRANT = [
  'DELETE',
  'INSERT',
  'MAINTAIN',
  'REFERENCES',
  'SELECT',
  'TRIGGER',
  'TRUNCATE',
  'UPDATE',
];

/** Shorthand for the 39 tables that share the default grant and the RLS gate. */
const defaultGrantTable = (name: string, why: string): AnonAllowlistEntry => ({
  kind: 'table',
  name,
  privileges: SUPABASE_DEFAULT_TABLE_GRANT,
  why,
});

/**
 * The reviewed set. Anything the live catalogue reports that is not here fails
 * the test, and so does anything here that the live catalogue reports with more
 * privileges than listed.
 */
export const ANON_ALLOWLIST: readonly AnonAllowlistEntry[] = [
  // -------------------------------------------------------------------------
  // Tables. Grant is the default ACL in every case; RLS is the control. Each
  // `why` says what the table holds and which gate keeps anon out of it.
  // -------------------------------------------------------------------------
  defaultGrantTable(
    'accounts',
    'The tenant root. Holds email, business_name and booking_ingest_secret, which is the shared secret the venue sites use to post booking conversions. RLS gates every command on is_account_member or the service role. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'ad_metrics_history',
    'Per-account paid performance history: impressions, clicks, ctr, frequency and spend. Commercially sensitive between tenants. Single RLS policy gated on the account. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'ad_sets',
    'Per-account Meta ad set records. Single RLS policy gated on the account. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'ads',
    'Per-account Meta ad records. Single RLS policy gated on the account. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'analytics_snapshots',
    'Per-account social performance snapshots including the raw provider payload in raw_data. Four RLS policies, all gated on the account. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'audit_log',
    'Per-account audit trail carrying user_id, resource ids and a correlation id. Two RLS policies gated on the account. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'auth_rate_limits',
    'Sign-in throttling counters. The only RLS policy requires auth.role() = service_role, so anon matches nothing for any command. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'booking_conversion_events',
    'Booking conversions forwarded from the venue websites, with booking ids, event names and dates. The only policy is a SELECT gated on is_account_member, so anon has no policy at all for writes. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'brand_profile',
    'Per-account brand voice: tone, key phrases, banned topics, default hashtags and the platform signatures. This is the customer intellectual property the product is built around. Single RLS policy gated on the account. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'campaigns',
    'Per-account campaign records. Two RLS policies gated on the account. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'content_item_versions',
    'Version history of generated content. Four RLS policies gated on the account. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'content_items',
    'The generated posts themselves, and the largest body of customer data in the database. Five RLS policies gated on the account. Verified: anon counts zero rows against 1212 owner-visible rows, which also proves the role switch in that check took effect.',
  ),
  defaultGrantTable(
    'content_media_attachments',
    'Joins content items to media. Four RLS policies gated on the account. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'content_templates',
    'Per-account content templates. Single RLS policy gated on the account. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'content_variants',
    'Per-platform variants of a content item. Single RLS policy gated on the account. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'link_in_bio_clicks',
    'Click analytics for the public link-in-bio pages. SELECT is gated on the owning account. INSERT is NOT gated: see the link_in_bio_clicks_service_insert entry in ANON_OPEN_ITEMS. The read side is what this entry allows, and it is verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'link_in_bio_page_views',
    'Page-view analytics for the public link-in-bio pages. SELECT is gated on the owning account. INSERT is NOT gated: see the link_in_bio_page_views_service_insert entry in ANON_OPEN_ITEMS. The read side is what this entry allows, and it is verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'link_in_bio_profiles',
    'The link-in-bio profile record. Despite the public page it backs, anon reads nothing: every policy is gated on is_account_member or the service role, because the public page is rendered server-side with the service-role client (src/lib/link-in-bio/click-tracking.ts). Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'link_in_bio_tiles',
    'The tiles shown on a link-in-bio page. Same shape as link_in_bio_profiles: served through the service role, not the anon key. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'management_app_connections',
    'Holds base_url and api_key in plain text for each tenant venue management app. A read here is a credential handover to a third system, so the RLS gate on this table matters more than most. Single policy gated on the account. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'media_assets',
    'Per-account media metadata, storage paths and derived variants. Single RLS policy gated on the account. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'media_library',
    'The older per-account media metadata table, including file_url. Four RLS policies gated on the account. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'meta_ad_accounts',
    'Linked Meta ad account identifiers per tenant. Single RLS policy gated on the account. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'meta_campaigns',
    'Local mirror of Meta campaigns per tenant. Single RLS policy gated on the account. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'meta_optimisation_actions',
    'Records of automated spend actions taken against a tenant ad account. Single RLS policy gated on the account. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'meta_optimisation_runs',
    'Log of optimisation runs. Single RLS policy gated on the account. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'notifications',
    'Per-account in-app notifications, including message and body text. Five RLS policies gated on the account. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'oauth_states',
    'Live OAuth handshakes: state, code_verifier and auth_code. This is short-lived credential material, and a readable row here is an account takeover on the linked social profile. Four RLS policies gated on the account. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'posting_defaults',
    'Per-account posting defaults, platform location ids and venue coordinates. Single RLS policy gated on the account. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'profiles',
    'Per-user profile inside an account: display name, avatar and brand voice defaults. Four RLS policies gated on the account. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'provider_rate_limits',
    'Per-account provider rate-limit counters. Three RLS policies, all gated on is_account_member, so anon can neither read nor write this table directly. It can still be written indirectly: see increment_rate_limit in ANON_OPEN_ITEMS. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'publish_attempts',
    'Per-job publish attempt log, including provider errors. Four RLS policies gated on the account. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'publish_jobs',
    'The publish queue. Five RLS policies gated on the account. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'social_connections',
    'The linked social accounts per tenant. Five RLS policies gated on the account. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'token_vault',
    'Encrypted social access tokens: ciphertext, iv, tag and key_version. The highest-value table in the database, and the reason the tenant boundary here is not negotiable. Four RLS policies gated on the account through social_connections. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'tournament_fixtures',
    'Fixture data behind the tournament content feature, reachable through the owning tournament account. Single RLS policy. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'tournaments',
    'Per-account tournament records. Single RLS policy gated on the account or the service role. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'user_auth_snapshot',
    'A mirror of auth.users holding email, status and last_sign_in_at. The strongest configuration in the schema: RLS is FORCED, and the single policy names authenticated and service_role explicitly, so anon has no policy at all rather than a policy it fails. Verified: anon counts zero rows.',
  ),
  defaultGrantTable(
    'worker_heartbeats',
    'Background worker liveness. The only policy requires auth.role() = service_role, so anon matches nothing. Verified: anon counts zero rows.',
  ),

  // -------------------------------------------------------------------------
  // Views.
  // -------------------------------------------------------------------------
  {
    kind: 'view',
    name: 'publish_jobs_with_variant',
    privileges: SUPABASE_DEFAULT_TABLE_GRANT,
    why: 'Joins publish_jobs to its content variant. Safe because it is declared security_invoker = true, so it runs with the caller rights and the RLS on the underlying tables applies to anon rather than to the view owner. A view without that setting would run as postgres and hand anon everything it selects, which is why the test reads views as well as tables. Verified: anon counts zero rows.',
  },

  // -------------------------------------------------------------------------
  // Extensions, rolled up. See the note in the header.
  // -------------------------------------------------------------------------
  {
    kind: 'extension',
    name: 'btree_gist',
    privileges: ['EXECUTE'],
    objects: 188,
    why: 'GiST index support routines, installed into public and granted to PUBLIC by the extension. They take and return internal index types and touch no application data. All 188 functions the extension owns in public are anon-executable, and the count is recorded so a version bump that adds functions fails this check rather than passing unseen.',
  },

  // -------------------------------------------------------------------------
  // Application functions. Only the ones anon may keep.
  // -------------------------------------------------------------------------
  {
    kind: 'function',
    name: 'current_account_id()',
    privileges: ['EXECUTE'],
    why: 'SECURITY INVOKER, so it holds no rights of its own. It reads the account id from the caller JWT and falls back to a lookup on accounts by auth.uid(). For anon both paths are null, so it returns null and reveals nothing. It is called from inside RLS policies, which is why the grant is wanted rather than merely tolerated.',
  },
  {
    kind: 'function',
    name: 'set_updated_at()',
    privileges: ['EXECUTE'],
    why: 'A trigger function. It returns trigger, so PostgREST does not expose it as an RPC, and calling it outside a trigger raises immediately. The grant is default-ACL residue rather than a decision. Harmless, but a future migration that tightens function grants should sweep it up with the rest.',
  },
  {
    kind: 'function',
    name: 'touch_link_in_bio_updated_at()',
    privileges: ['EXECUTE'],
    why: 'A trigger function, same reasoning as set_updated_at(). Returns trigger, not exposed as an RPC, default-ACL residue rather than a decision.',
  },
];

/**
 * Names that must never appear in `ANON_ALLOWLIST`, whatever the live catalogue
 * says. Functions are matched on the bare name so every overload is covered;
 * relations are matched on the relation name.
 *
 * These are the tenant boundary itself and the SECURITY DEFINER functions that
 * cross it. A SECURITY DEFINER function that accepts an account id runs with the
 * owner rights, so RLS does not apply and the account id is whatever the caller
 * chose to send. Granting anon EXECUTE on one of those is the same as granting
 * anon direct write access to every tenant at once.
 *
 * The test asserts the allowlist contains none of them. If the live database
 * grants one, the fix is a migration that revokes it from PUBLIC and anon
 * together, in the same migration that creates the object.
 */
export const NEVER_ALLOWLIST: readonly string[] = [
  // The tenant and admin gate itself. Every RLS policy in the schema depends on
  // these two answering honestly.
  'is_account_member',
  'is_super_admin',
  // The tables those two read. Revoked from anon by 20260714120000, and they
  // must stay revoked: account_members is the membership map, app_admins is the
  // super-admin registry, admin_audit is the cross-tenant admin trail.
  'account_members',
  'app_admins',
  'admin_audit',
  // SECURITY DEFINER functions that take an account id and act on it. Each one
  // bypasses RLS by design, so anon EXECUTE on any of them is a cross-tenant
  // write.
  'increment_rate_limit',
  'reserve_imported_media_asset',
  'finalise_imported_media_asset',
  'release_imported_media_asset',
  // SECURITY DEFINER functions over auth user data and worker internals.
  'purge_user_auth_snapshot',
  'sync_user_auth_snapshot',
  'inspect_worker_db_context',
  // A test fixture that takes an advisory lock. Never a public entry point.
  'advisory_lock_fixture',
];

/**
 * Anon reach that has been reviewed, is NOT approved, and has not been closed
 * yet. Listing it here does not allow it: the test still fails on it. The point
 * is that the failure reads as a known open item with a decision attached rather
 * than as a fresh regression, and that it stays visible until it is dealt with.
 *
 * Closing any of these means writing a migration, which is a deliberate act with
 * its own review. Nothing in this file changes a grant.
 */
export interface AnonOpenItem {
  kind: AnonObjectKind;
  name: string;
  why: string;
}

export const ANON_OPEN_ITEMS: readonly AnonOpenItem[] = [
  {
    kind: 'function',
    name: 'increment_rate_limit(p_account_id uuid, p_provider text, p_endpoint text, p_window_start timestamp with time zone, p_limit_ceiling integer)',
    why: [
      'CROSSES THE TENANT BOUNDARY. A SECURITY DEFINER function that upserts into',
      'provider_rate_limits using the p_account_id the caller supplies, with no',
      'membership check of any kind. Definer rights mean RLS does not apply. Anyone',
      'holding the public anon key, which ships in every browser bundle, can call it',
      'over PostgREST as POST /rest/v1/rpc/increment_rate_limit and increment the',
      'request_count of any tenant they can name, which is enough to rate-limit that',
      "tenant's publishing. provider_rate_limits.account_id also carries a foreign",
      'key to accounts, so the call succeeds for a real account id and errors for an',
      'invented one, which turns the same endpoint into an account-id oracle.',
      'Migration 20260527080658_lockdown_admin_functions_2026_05_27.sql already',
      'tried to close this and did not: it revoked FROM anon but not FROM PUBLIC,',
      'and create function grants PUBLIC its own EXECUTE. The live catalogue',
      'confirms both grants are present today. The fix is one migration that runs',
      'revoke execute on function ... from public, anon.',
    ].join(' '),
  },
  {
    kind: 'function',
    name: 'is_account_member(target uuid)',
    why: [
      'Configuration drift against an explicit decision, with no data impact today.',
      'Migration 20260714120000_multibrand_foundation.sql revoked this FROM public',
      'and granted it only to authenticated and service_role, so the intent that anon',
      'should not hold it is on the record. The revoke did not reach anon, because',
      "pg_default_acl had already granted anon EXECUTE directly, and revoking PUBLIC",
      'does not touch a direct grant. The live catalogue shows anon EXECUTE present',
      'and PUBLIC EXECUTE absent, which is the signature of exactly that.',
      'Not currently exploitable: the body reads auth.uid(), which is null for anon,',
      'so it returns false for every input and leaks nothing. It is listed here',
      'rather than allowlisted because this function IS the tenant gate, and a grant',
      'on it that nobody intended should not be blessed by a file that claims to be',
      'the reviewed state. The fix is a migration adding',
      'revoke execute on function public.is_account_member(uuid) from anon.',
    ].join(' '),
  },
  {
    kind: 'function',
    name: 'is_super_admin()',
    why: [
      'Same cause and same shape as is_account_member(uuid), from the same migration',
      'and the same missing half of the revoke. Reads app_admins by auth.uid(), which',
      'is null for anon, so it returns false for every caller and leaks nothing today.',
      'Listed rather than allowlisted for the same reason: it is part of the tenant',
      'and admin gate. The fix is a migration adding',
      'revoke execute on function public.is_super_admin() from anon.',
    ].join(' '),
  },
];

/**
 * Reach that this check cannot see, recorded so it is not mistaken for absence.
 *
 * The catalogue query answers "what can anon do to this object", which is a
 * question about GRANTs. It does not answer "what rows does RLS then let anon
 * touch", which is a question about POLICIES. A permissive policy on a table
 * anon already holds a grant on is just as reachable as a grant, and it will not
 * appear as a finding below.
 */
export const ANON_POLICY_OPEN_ITEMS: readonly AnonOpenItem[] = [
  {
    kind: 'table',
    name: 'link_in_bio_clicks (policy link_in_bio_clicks_service_insert)',
    why: [
      'CROSSES THE TENANT BOUNDARY. The policy is named service_insert but it has no',
      'TO clause, so it applies to PUBLIC, and its check expression is literally',
      'true. Combined with the INSERT privilege anon holds from the default ACL, any',
      'holder of the public anon key can insert click rows against any profile_id,',
      "including another customer's. The comment above it in",
      '00000000000009_link_in_bio_reconcile.sql reads "Service-role INSERT", so the',
      'intent was service-role only; the code agrees, since',
      'src/lib/link-in-bio/click-tracking.ts inserts through the service-role client.',
      'The effect is corrupted analytics for an arbitrary tenant rather than a data',
      'read. The fix is a migration that recreates the policy with',
      "TO service_role, or a check on auth.role() = 'service_role'.",
    ].join(' '),
  },
  {
    kind: 'table',
    name: 'link_in_bio_page_views (policy link_in_bio_page_views_service_insert)',
    why: [
      'Identical to link_in_bio_clicks_service_insert, from the same migration: no TO',
      'clause, check expression true, and anon holds INSERT. Any holder of the anon',
      "key can inflate any tenant's page-view counts. Same fix.",
    ].join(' '),
  },
];

/**
 * The catalogue query the test runs against the live database. Read-only.
 *
 * It asks `has_*_privilege` rather than reading ACL arrays, because that is the
 * question worth answering: what anon can actually do, including anything it
 * inherits through PUBLIC. That distinction is not academic here, since one of
 * the two failed lockdowns left the reach behind exactly that inheritance.
 *
 * Functions are keyed by identity arguments so an overload cannot hide behind a
 * sibling with the same name. Extension-owned functions are rolled up per
 * extension with a count, for the reason given in the header.
 */
export const ANON_CATALOGUE_QUERY = `
with table_privs as (
  select case when current_setting('server_version_num')::int >= 170000
              then array[${TABLE_PRIVILEGES_PG17.map((p) => `'${p}'`).join(',')}]
              else array[${TABLE_PRIVILEGES.map((p) => `'${p}'`).join(',')}] end as names
),
rel as (
  select case c.relkind when 'r' then 'table' when 'p' then 'table'
                        when 'v' then 'view' when 'm' then 'materialized view' end as kind,
         c.relname as name,
         (select coalesce(array_agg(p order by p), array[]::text[])
            from table_privs, unnest(table_privs.names) p
           where has_table_privilege('anon', c.oid, p)) as privileges,
         null::int as objects
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public' and c.relkind in ('r','p','v','m')
),
seq as (
  select 'sequence' as kind, c.relname as name,
         (select coalesce(array_agg(p order by p), array[]::text[])
            from unnest(array[${SEQUENCE_PRIVILEGES.map((p) => `'${p}'`).join(',')}]) p
           where has_sequence_privilege('anon', c.oid, p)) as privileges,
         null::int as objects
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public' and c.relkind = 'S'
),
app_fn as (
  select 'function' as kind,
         p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')' as name,
         array['EXECUTE'] as privileges,
         null::int as objects
    from pg_proc p
    left join pg_depend d
      on d.classid = 'pg_proc'::regclass and d.objid = p.oid and d.deptype = 'e'
   where p.pronamespace = 'public'::regnamespace
     and d.objid is null
     and has_function_privilege('anon', p.oid, 'EXECUTE')
),
ext_fn as (
  select 'extension' as kind, e.extname as name,
         array['EXECUTE'] as privileges,
         count(*)::int as objects
    from pg_proc p
    join pg_depend d
      on d.classid = 'pg_proc'::regclass and d.objid = p.oid and d.deptype = 'e'
    join pg_extension e on e.oid = d.refobjid
   where p.pronamespace = 'public'::regnamespace
     and has_function_privilege('anon', p.oid, 'EXECUTE')
   group by e.extname
)
select coalesce(json_agg(row_to_json(x) order by x.kind, x.name), '[]'::json) as reachable
  from (
    select * from rel where cardinality(privileges) > 0
    union all select * from seq where cardinality(privileges) > 0
    union all select * from app_fn
    union all select * from ext_fn
  ) x;
`.trim();

/** One way the live database is wider than the allowlist. */
export interface AnonAccessFinding {
  kind: AnonObjectKind;
  name: string;
  /**
   * `unlisted` is an object anon can reach that the allowlist does not mention.
   * `widened` is a listed object holding privileges beyond those allowed.
   * `grew` is a listed extension contributing more functions than allowed.
   */
  problem: 'unlisted' | 'widened' | 'grew';
  extraPrivileges: string[];
  /** Set on `grew`: the live count, against the allowlisted count. */
  liveObjects?: number;
  allowedObjects?: number;
  /** Set when this object is a reviewed, still-open item rather than new drift. */
  knownOpenItem?: string;
}

export interface AnonAccessDiff {
  findings: AnonAccessFinding[];
  /**
   * Allowlisted objects the live database no longer grants, or grants less of.
   * Not a failure: the world got tighter. Reported so the file can be trimmed.
   */
  stale: string[];
}

const keyOf = (kind: string, name: string): string => `${kind} ${name}`;

/**
 * Compare a live catalogue reading against the allowlist. Pure, so the rules are
 * unit-tested without a database.
 */
export function diffAnonAccess(
  reachable: readonly AnonCatalogueEntry[],
  allowlist: readonly AnonAllowlistEntry[] = ANON_ALLOWLIST,
  openItems: readonly AnonOpenItem[] = ANON_OPEN_ITEMS,
): AnonAccessDiff {
  const allowed = new Map<string, AnonAllowlistEntry>(
    allowlist.map((entry) => [keyOf(entry.kind, entry.name), entry]),
  );
  const open = new Map<string, AnonOpenItem>(
    openItems.map((item) => [keyOf(item.kind, item.name), item]),
  );

  const findings: AnonAccessFinding[] = [];
  const seen = new Set<string>();

  for (const entry of reachable) {
    const key = keyOf(entry.kind, entry.name);
    seen.add(key);
    const allowedEntry = allowed.get(key);

    if (!allowedEntry) {
      const openItem = open.get(key);
      findings.push({
        kind: entry.kind,
        name: entry.name,
        problem: 'unlisted',
        extraPrivileges: [...entry.privileges].sort(),
        ...(openItem ? { knownOpenItem: openItem.why } : {}),
      });
      continue;
    }

    const permitted = new Set(allowedEntry.privileges);
    const extra = entry.privileges.filter((p) => !permitted.has(p)).sort();
    if (extra.length > 0) {
      findings.push({
        kind: entry.kind,
        name: entry.name,
        problem: 'widened',
        extraPrivileges: extra,
      });
      continue;
    }

    const liveObjects = entry.objects ?? 0;
    const allowedObjects = allowedEntry.objects ?? 0;
    if (liveObjects > allowedObjects) {
      findings.push({
        kind: entry.kind,
        name: entry.name,
        problem: 'grew',
        extraPrivileges: [],
        liveObjects,
        allowedObjects,
      });
    }
  }

  const stale = [...allowed.keys()].filter((key) => !seen.has(key)).sort();

  return { findings, stale };
}

/** A failure message that names the objects and says what to do about them. */
export function describeAnonAccessFindings(
  findings: readonly AnonAccessFinding[],
): string {
  const lines = [
    `anon can reach ${findings.length} object(s) that supabase/anon-access-allowlist.ts does not allow.`,
    '',
  ];

  for (const finding of findings) {
    if (finding.problem === 'unlisted') {
      lines.push(
        `  NOT ALLOWLISTED  ${finding.kind} ${finding.name}`,
        `                   anon holds: ${finding.extraPrivileges.join(', ')}`,
      );
      if (finding.knownOpenItem) {
        lines.push(
          '                   This is a reviewed, still-open item, not new drift:',
          `                   ${finding.knownOpenItem}`,
        );
      }
    } else if (finding.problem === 'widened') {
      lines.push(
        `  WIDENED          ${finding.kind} ${finding.name}`,
        `                   anon gained: ${finding.extraPrivileges.join(', ')}`,
      );
    } else {
      lines.push(
        `  GREW             ${finding.kind} ${finding.name}`,
        `                   anon can execute ${finding.liveObjects} function(s), allowlist says ${finding.allowedObjects}`,
      );
    }
    lines.push('');
  }

  lines.push(
    'Do not edit the allowlist to make this pass. Find the migration that changed',
    'the database. If the reach is wanted, add it to the allowlist with a reason in',
    'the same pull request. If it is not, write a migration that revokes it, from',
    'PUBLIC and anon together, because create function grants PUBLIC its own EXECUTE',
    'and the project default ACL grants anon its own EXECUTE. Revoking only one of',
    'the two leaves the reach in place, which is how both earlier lockdowns in this',
    'repository failed.',
    '',
    'Nothing that crosses a tenant boundary may be added to the allowlist. This is a',
    'multi-tenant database and one customer reaching another customer data is a',
    'breach, not a configuration choice.',
  );

  return lines.join('\n');
}
