// @vitest-environment jsdom
import type { ReactNode } from "react";
import { cleanup, render, screen, within } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";

import type { PlannerContentDetail } from "@/lib/planner/data";

const CONTENT_ID = "0b6f5f4e-1c2d-4a3b-9e8f-7a6b5c4d3e2f";

const getPlannerContentDetail = vi.hoisted(() => vi.fn());

vi.mock("@/lib/planner/data", () => ({ getPlannerContentDetail }));
vi.mock("@/lib/library/data", () => ({ listMediaAssets: vi.fn().mockResolvedValue([]) }));
vi.mock("@/lib/settings/data", () => ({
  getOwnerSettings: vi.fn().mockResolvedValue({ posting: { timezone: "Europe/London" } }),
}));
vi.mock("next/navigation", () => ({ notFound: vi.fn() }));
vi.mock("next/link", () => ({
  default: ({ href, children, ...rest }: { href: string; children: ReactNode }) => (
    <a href={href} {...rest}>{children}</a>
  ),
}));

// The cards below have their own tests; here they only need to render.
vi.mock("@/features/planner/planner-content-composer", () => ({ PlannerContentComposer: () => <div /> }));
vi.mock("@/features/planner/content-schedule-form", () => ({ PlannerContentScheduleForm: () => <div /> }));
vi.mock("@/features/planner/planner-media-swap-button", () => ({ PlannerMediaSwapButton: () => <div /> }));
vi.mock("@/features/planner/belongs-to-card", () => ({ BelongsToCard: () => <div /> }));
vi.mock("@/components/media/media-frame", () => ({ MediaFrameImage: () => <div />, MediaFrameVideo: () => <div /> }));
vi.mock("@/features/planner/planner-post-actions", () => ({
  PublishNowButton: ({ label = "Publish now" }: { label?: string }) => <button type="button">{label}</button>,
  CancelPostButton: () => <button type="button">Cancel this post</button>,
}));

function makeDetail(overrides: Partial<PlannerContentDetail> = {}): PlannerContentDetail {
  return {
    id: CONTENT_ID,
    platform: "facebook",
    placement: "feed",
    status: "scheduled",
    scheduledFor: "2026-10-03T11:00:00.000Z",
    body: "Sunday roast is back this weekend.",
    mediaIds: [],
    campaign: { id: null, name: "Sunday roast", campaignType: null, metadata: null },
    autoGenerated: false,
    promptContext: null,
    media: [],
    lastError: null,
    lastAttemptedAt: null,
    providerResponse: null,
    bannerConfig: { enabled: false, position: "right", bgColour: "#a57626", textColour: "#ffffff", textOverride: null },
    bannerLabel: null,
    bannerOverrides: {
      banner_enabled: null,
      banner_text_override: null,
      banner_position: null,
      banner_bg: null,
      banner_text_colour: null,
    },
    accountBannerDefaults: {
      banners_enabled: false,
      banner_position: "right",
      banner_bg: "#a57626",
      banner_text_colour: "#ffffff",
    },
    ...overrides,
  };
}

async function renderPage(detail: PlannerContentDetail) {
  getPlannerContentDetail.mockResolvedValue(detail);
  const { default: PlannerContentPage } = await import("./page");
  render(await PlannerContentPage({ params: Promise.resolve({ contentId: CONTENT_ID }) }));
}

function buttonLabels(): string[] {
  return screen.queryAllByRole("button").map((button) => button.textContent?.trim() ?? "");
}

/** Buttons that had no handler and were removed rather than left dead. */
const REMOVED = ["Save changes", "Download copy & image", "Regenerate", "Try a different angle"];

afterEach(() => {
  cleanup();
  vi.clearAllMocks();
});

describe("planner post page actions", () => {
  it("offers Cancel and Publish now on a scheduled post, and none of the removed buttons", async () => {
    await renderPage(makeDetail({ status: "scheduled" }));

    const footer = screen.getByRole("contentinfo");
    expect(within(footer).getAllByRole("button").map((b) => b.textContent)).toEqual(["Cancel this post", "Publish now"]);
    for (const label of REMOVED) {
      expect(buttonLabels()).not.toContain(label);
    }
  });

  it("offers Reconnect and Try again now on a failed post, with no second publish button in the footer", async () => {
    await renderPage(makeDetail({ status: "failed", lastError: "Facebook rejected the post." }));

    expect(screen.getByRole("link", { name: /Reconnect Facebook/ })).toHaveAttribute("href", "/connections");
    expect(screen.getByRole("button", { name: "Try again now" })).toBeInTheDocument();

    const footer = screen.getByRole("contentinfo");
    expect(within(footer).getAllByRole("button").map((b) => b.textContent)).toEqual(["Cancel this post"]);
    for (const label of REMOVED) {
      expect(buttonLabels()).not.toContain(label);
    }
  });

  it.each(["draft", "queued"] as const)("offers only Cancel on a %s post", async (status) => {
    await renderPage(makeDetail({ status }));

    const footer = screen.getByRole("contentinfo");
    expect(within(footer).getAllByRole("button").map((b) => b.textContent)).toEqual(["Cancel this post"]);
    expect(buttonLabels()).not.toContain("Publish now");
  });

  it.each(["publishing", "posted"] as const)("offers no footer actions on a %s post", async (status) => {
    await renderPage(makeDetail({ status }));

    expect(screen.queryByRole("contentinfo")).toBeNull();
    expect(buttonLabels()).not.toContain("Cancel this post");
    expect(buttonLabels()).not.toContain("Publish now");
  });
});
