// @vitest-environment jsdom
import type { ReactNode } from "react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";

import { PostDrawer } from "@/features/planner/post-drawer";
import type { PlannerContentDetail } from "@/lib/planner/data";

const routerRefresh = vi.hoisted(() => vi.fn());

vi.mock("next/navigation", () => ({
  useRouter: () => ({ refresh: routerRefresh }),
}));

vi.mock("@/components/providers/toast-provider", () => ({
  useToast: () => ({
    success: vi.fn(),
    error: vi.fn(),
    info: vi.fn(),
    dismiss: vi.fn(),
  }),
}));

vi.mock("@/components/ui/sheet", () => ({
  Sheet: ({ open, children }: { open: boolean; children: ReactNode }) => (open ? <div>{children}</div> : null),
  SheetContent: ({ children }: { children: ReactNode }) => <div>{children}</div>,
  SheetHeader: ({ children }: { children: ReactNode }) => <div>{children}</div>,
  SheetTitle: ({ children }: { children: ReactNode }) => <h2>{children}</h2>,
  SheetDescription: ({ children }: { children: ReactNode }) => <p>{children}</p>,
}));

vi.mock("@/features/planner/banner-overlay", () => ({
  BannerOverlay: () => <div data-testid="banner-overlay" />,
}));

vi.mock("@/features/planner/planner-media-swap-button", () => ({
  PlannerMediaSwapButton: ({
    ariaLabel,
    buttonLabel,
    contentId,
    onUpdated,
  }: {
    ariaLabel?: string;
    buttonLabel?: string;
    contentId: string;
    onUpdated?: (contentId: string) => void | Promise<void>;
  }) => (
    <button type="button" aria-label={ariaLabel} onClick={() => void onUpdated?.(contentId)}>
      {buttonLabel}
    </button>
  ),
}));

function makeContent(overrides: Partial<PlannerContentDetail> = {}): PlannerContentDetail {
  return {
    id: "content-1",
    platform: "instagram",
    placement: "feed",
    status: "scheduled",
    scheduledFor: "2026-07-04T07:00:00.000Z",
    body: "Post copy",
    mediaIds: ["media-1"],
    campaign: {
      id: null,
      name: "Campaign",
      campaignType: null,
      metadata: null,
    },
    autoGenerated: false,
    promptContext: null,
    media: [
      {
        id: "media-1",
        url: "https://example.com/media.jpg",
        mediaType: "image",
        fileName: "media.jpg",
      },
    ],
    lastError: null,
    lastAttemptedAt: null,
    providerResponse: null,
    bannerConfig: {
      enabled: false,
      position: "right",
      bgColour: "#a57626",
      textColour: "#ffffff",
      textOverride: null,
    },
    bannerLabel: null,
    bannerOverrides: {
      banner_enabled: null,
      banner_text_override: null,
      banner_position: null,
      banner_bg: null,
      banner_text_colour: null,
    },
    accountBannerDefaults: {
      banners_enabled: false,
      banner_position: "right",
      banner_bg: "#a57626",
      banner_text_colour: "#ffffff",
    },
    ...overrides,
  };
}

function renderDrawer(content: PlannerContentDetail) {
  const queryClient = new QueryClient({
    defaultOptions: {
      queries: { retry: false },
    },
  });
  const invalidateSpy = vi.spyOn(queryClient, "invalidateQueries");

  vi.stubGlobal(
    "fetch",
    vi.fn().mockResolvedValue({
      ok: true,
      json: async () => content,
    }),
  );

  render(
    <QueryClientProvider client={queryClient}>
      <PostDrawer contentId="content-1" open onOpenChange={vi.fn()} />
    </QueryClientProvider>,
  );

  return { invalidateSpy };
}

describe("<PostDrawer /> media editing", () => {
  afterEach(() => {
    cleanup();
    vi.unstubAllGlobals();
    vi.clearAllMocks();
  });

  it("shows an edit button for media on editable posts", async () => {
    renderDrawer(makeContent());

    expect(await screen.findByText("Media (1)")).toBeInTheDocument();
    expect(screen.getByRole("button", { name: /edit media/i })).toBeInTheDocument();
  });

  it("refreshes the drawer query and planner after media is saved", async () => {
    const { invalidateSpy } = renderDrawer(makeContent());

    await screen.findByText("Media (1)");
    fireEvent.click(screen.getByRole("button", { name: /edit media/i }));

    await waitFor(() => {
      expect(invalidateSpy).toHaveBeenCalledWith({ queryKey: ["content-detail", "content-1"] });
    });
    expect(routerRefresh).toHaveBeenCalled();
  });
});

/*
 * Pinning tests for the `canEdit={canEdit && content.placement !== 'story'}`
 * guard in post-drawer.tsx. That guard is on <InlineCopyEditor>, so it gates
 * the caption, NOT the image overlay. Do not "fix" it by dropping the placement
 * check to make story overlays editable: overlays are edited through
 * <BannerControls> in planner-content-composer.tsx, which has no placement
 * guard and already allows it, gated only by BANNER_EDITABLE_STATUSES.
 *
 * Removing the check here would introduce a silent-discard bug.
 * updatePlannerContentBody (src/app/(app)/planner/actions.ts:1000-1005) forces
 * an empty body when placement is "story", so a user could type a story
 * caption, save it, see a "Copy updated" toast, and lose the text.
 *
 * Both cases below use status "scheduled", which IS editable, so a failure here
 * points at the placement guard rather than at status gating.
 */
describe("<PostDrawer /> story caption gating", () => {
  afterEach(() => {
    cleanup();
    vi.unstubAllGlobals();
    vi.clearAllMocks();
  });

  it("keeps the caption read-only on a scheduled story", async () => {
    renderDrawer(makeContent({ placement: "story", status: "scheduled", body: "" }));

    const copyHeading = await screen.findByText("Copy");
    const copySection = copyHeading.parentElement!;
    expect(within(copySection).queryByRole("button", { name: /edit/i })).toBeNull();
    expect(screen.getByText(/stories publish without captions/i)).toBeInTheDocument();
    expect(screen.queryByRole("button", { name: /add copy/i })).toBeNull();
  });

  it("keeps the caption editable on a feed post at the same status", async () => {
    renderDrawer(makeContent({ placement: "feed", status: "scheduled" }));

    const copyHeading = await screen.findByText("Copy");
    const copySection = copyHeading.parentElement!;
    expect(within(copySection).getByRole("button", { name: /edit/i })).toBeInTheDocument();
  });
});
