/**
 * Recurring auto-publish dispatch (06-05, SCHED-04).
 * Finds content_items with auto_confirm=true and auto_generated=true that are
 * due for publishing, creates publish_jobs, and dispatches to QStash.
 *
 * D-13: Auto-published items are dispatched silently (no notification).
 * Idempotency: skips items where a publish_job already exists.
 */

import { dispatchToQStash } from '@/lib/publishing/dispatch';
import { transitionStatus } from '@/lib/publishing/state-machine';
import { tryCreateServiceSupabaseClient } from '@/lib/supabase/service';

interface DispatchResult {
  dispatched: number;
  skipped: number;
  errors: string[];
}

interface DueContentItem {
  id: string;
  campaign_id: string;
  platform: string;
  scheduled_for: string;
  account_id: string;
}

/**
 * Find all due auto-confirm content items and dispatch them to QStash for publishing.
 *
 * Query criteria:
 * - auto_confirm = true (recurring campaigns with permanent approval)
 * - auto_generated = true (generated by materialisation, not manual)
 * - status = 'scheduled' (ready for dispatch, not already queued)
 * - scheduled_for <= NOW() (due or overdue)
 *
 * For each due item:
 * 1. Check idempotency: skip if publish_job already exists
 * 2. Create publish_job with status 'queued'
 * 3. Transition content_item from 'scheduled' to 'queued'
 * 4. Dispatch to QStash
 *
 * Errors for individual items are caught and accumulated -- processing
 * continues for remaining items.
 */
export async function dispatchRecurringPublishes(): Promise<DispatchResult> {
  const supabase = tryCreateServiceSupabaseClient();

  if (!supabase) {
    return { dispatched: 0, skipped: 0, errors: [] };
  }

  // Find all due auto-confirm items
  const { data: dueItems, error: queryError } = await supabase
    .from('content_items')
    .select('id, campaign_id, platform, scheduled_for, account_id')
    .eq('auto_confirm', true)
    .eq('auto_generated', true)
    .eq('status', 'scheduled')
    .lte('scheduled_for', new Date().toISOString());

  if (queryError) {
    return { dispatched: 0, skipped: 0, errors: [queryError.message] };
  }

  if (!dueItems || dueItems.length === 0) {
    return { dispatched: 0, skipped: 0, errors: [] };
  }

  let dispatched = 0;
  let skipped = 0;
  const errors: string[] = [];

  for (const item of dueItems as DueContentItem[]) {
    try {
      // Idempotency check: skip if a publish_job already exists
      const { data: existingJobs } = await supabase
        .from('publish_jobs')
        .select('id')
        .eq('content_item_id', item.id)
        .eq('platform', item.platform)
        .limit(1);

      if (existingJobs && existingJobs.length > 0) {
        skipped++;
        continue;
      }

      // Create publish_job with status 'queued'
      const idempotencyKey = `${item.id}:${item.platform}:${Date.now()}`;
      const { data: publishJob, error: insertError } = await supabase
        .from('publish_jobs')
        .insert({
          content_item_id: item.id,
          account_id: item.account_id,
          platform: item.platform,
          status: 'queued',
          idempotency_key: idempotencyKey,
          scheduled_at: item.scheduled_for,
        })
        .select('id, idempotency_key')
        .single();

      if (insertError || !publishJob) {
        throw new Error(
          `Failed to create publish_job for ${item.id}: ${insertError?.message ?? 'no data returned'}`,
        );
      }

      // Transition content_item status from 'scheduled' to 'queued'
      await transitionStatus(supabase, 'content_items', item.id, 'scheduled', 'queued');

      // Dispatch to QStash for async processing (D-13: silent, no notification)
      await dispatchToQStash({
        jobId: publishJob.id as string,
        deduplicationId: publishJob.idempotency_key as string,
      });

      dispatched++;
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      errors.push(`[${item.id}] ${message}`);
      console.error(`[recurring-dispatch] Error dispatching item ${item.id}:`, message);
    }
  }

  console.log(
    `[recurring-dispatch] Complete: dispatched=${dispatched}, skipped=${skipped}, errors=${errors.length}`,
  );

  return { dispatched, skipped, errors };
}
